- name: 'Update apt cache'
  apt:
    update_cache: True
  when: ansible_os_family == 'Debian'
- name: 'Install dependencies'
  apt:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ dependencies }}'