- block:
  - name: Download Kubernetes' official GPG key
    get_url:
      url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
      dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
      mode: '0644'

  - name: Add Kubernetes repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      filename: kubernetes

  - name: Install Kubernetes packages
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: present

  - name: Hold Kubernetes packages
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop: ['kubelet', 'kubeadm', 'kubectl']
    notify: Start and enable kubelet service
  
  rescue:
  - name: Remove GPG key
    file: 
      path: /etc/apt/keyrings/kubernetes-apt-keyring.asc
      state: absent

  - name: Remove kubernetes repository
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
      filename: kubernetes
      state: absent
  
  - name: Remove kubernetes packages
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
      state: absent