#!myansible/bin/ansible-playbook

- hosts: "ENV_{{ ENVIRONMENT | default('DEV') }}"
  become: True
  tasks:
    - name: 'Update apt cache'
      apt:
        update_cache: True

    - name: 'nginx install'
      apt:
        name: 'nginx'
        state: 'present'

    - name: 'start nginx'
      service:
        name: 'nginx'
        state: 'started'

  # import_playbook: playbook.yml